export const EXAMPLE = ''

export const data = [
  {
    id: 1,
    title: '«Нутрицевтическая подготовка к беременности»',
    subtitle: 'Первичная, Онлайн',
    patient: { name: 'Сергей К.', surname: 'Лазарченко' },
    date: { day: '14 февраля, вчера', time: '15:00' },
    conclusion: false,
    notification: true,
    expired: true,
  },
  {
    id: 2,
    title: '«Нутрицевтическая подготовка к беременности»',
    subtitle: 'Первичная, Онлайн',
    patient: { name: 'Сергей К.', surname: 'Лазарченко' },
    date: { day: '14 февраля, вчера', time: '15:00' },
    conclusion: false,
    notification: true,
    expired: false,
  },
  {
    id: 3,
    title: '«Нутрицевтическая подготовка к беременности»',
    subtitle: 'Первичная, Онлайн',
    patient: { name: 'Сергей К.', surname: 'Лазарченко' },
    date: { day: '14 февраля, вчера', time: '15:00' },
    conclusion: false,
    notification: false,
    expired: false,
  },
  {
    id: 4,
    title: '«Нутрицевтическая подготовка к беременности»',
    subtitle: 'Первичная, Онлайн',
    patient: { name: 'Сергей К.', surname: 'Лазарченко' },
    date: { day: '14 февраля, вчера', time: '15:00' },
    conclusion: true,
    notification: false,
    expired: false,
  },
]

export const data1 = [
  {
    id: 1,
    description: 'Нутрицевтическая подготовка к беременности',
    type: 'Первичная',
    complete: false,
    patient: { name: 'Ольга В.', surname: 'Ракова' },
    date: { time: '11:00' },
    online: true,
    notification: true,
    conclusion: false,
  },
  {
    id: 2,
    description: 'Нутрицевтическая подготовка к беременности',
    type: 'Первичная',
    complete: false,
    patient: { name: 'Ольга В.', surname: 'Ракова' },
    date: { time: '11:00' },
    online: false,
    notification: false,
    conclusion: false,
  },
  {
    id: 3,
    description: 'Нутрицевтическая подготовка к беременности',
    type: 'Первичная',
    complete: true,
    patient: { name: 'Ольга В.', surname: 'Ракова' },
    date: { time: '11:00' },
    online: false,
    notification: false,
    conclusion: false,
  },
  {
    id: 4,
    description: 'Нутрицевтическая подготовка к беременности',
    type: 'Первичная',
    complete: true,
    patient: { name: 'Ольга В.', surname: 'Ракова' },
    date: { time: '11:00' },
    online: false,
    notification: false,
    conclusion: true,
  },
]

export const data2 = [
  {
    id: 1,
    date: '20 февраля, пн',
    count: '2',
    entrys: [
      {
        id: 1,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
      {
        id: 2,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
    ],
  },
  {
    id: 2,
    date: '20 февраля, пн',
    count: '2',
    entrys: [
      {
        id: 1,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
      {
        id: 2,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
    ],
  },
  {
    id: 3,
    date: '20 февраля, пн',
    count: '2',
    entrys: [
      {
        id: 1,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
      {
        id: 2,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
    ],
  },
  {
    id: 4,
    date: '20 февраля, пн',
    count: '2',
    entrys: [
      {
        id: 1,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
      {
        id: 2,
        description: 'Нутрицевтическая подготовка к беременности',
        type: 'Первичная',
        complete: false,
        patient: { name: 'Ольга В.', surname: 'Ракова' },
        date: { time: '11:00' },
        online: true,
        notification: true,
        conclusion: false,
      },
    ],
  },
]

export const weeks = [
  { id: '1', date: '20 февраля, пн', count: 6 },
  { id: '2', date: '20 февраля, пн', count: 6 },
  { id: '3', date: '20 февраля, пн', count: 6 },
  { id: '4', date: '20 февраля, пн', count: 6 },
  { id: '5', date: '20 февраля, пн', count: 6 },
]
